global:
    dbConnectionString: postgresql://postgres:postgres@localhost/fileIndexer
    #sqliteDir: db
    fileHandleModules:
        - public.modules.CoreModule
    fileSystemModules:
        - public.modules.LocalFileSystemModule
    workersCount: 2
    

core:
    workers: 4
