global:
    #connectionString: sqlite:///db/core.db
    sqlite:
        sqlite_dir: db
    modules:
        - public.modules.coreModule
    fsModules:
        - public.modules.localFileSystemModule

core:
    workers: 4
