global:
    dbConnectionString: postgresql://postgres:postgres@localhost/fileIndexer
    #sqliteDir: db
    fileHandleModules:
        - modules.audioFileModule.AudioFileModule
        - modules.videoFileModule.VideoFileModule
        - modules.imageFileModule.ImageFileModule
    fileSystemModules:
        - public.modules.LocalFileSystemModule
    workersCount: 2
    dataSources:
        - file:///home/dademo/Musique
        - /home/dademo/Vidéos

core:
    workers: 4
