global:
    dbConnectionString: postgresql://postgres:postgres@localhost/fileIndexer
    #sqliteDir: db
    fileHandleModules:
        - modules.audioFileModule.AudioFileModule
        - modules.videoFileModule.VideoFileModule
        - modules.imageFileModule.ImageFileModule
    fileSystemModules:
        - public.modules.LocalFileSystemModule
    workersCount: 2
    dataSources:
        - path: file:///home/dademo/Musique
          ignorePatterns:
            - "*/.git/*"
            - "*/node_modules/*"
            - "*/.gem/**"
            - "*/vendor/**"
            - "*/lib/*"
            - "*/lib64/*"
            - "*/bin/*"
        - /home/dademo/Vidéos

core:
    workers: 4
